# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Sensor Calibrator's Toolbox
tagline:          'A Jekyll theme'
description:      'Making sensor calibration cool again'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mohammad Saad'
  url:            https://twitter.com/mohsaad230

paginate:         5

gems: ['jekyll-paginate']

port: 8000

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
